language: csharp

# runtime config
mono: none
dotnet: 3.0.100
dist: bionic

# branch build config
branches:
    only:        
        - master
        - preview
        - dev

    except:
        - gh-pages

# git config
git:
    depth: 1
    lfs_skip_smudge: true # disable the download of LFS objects when cloning

script:
    - bash build.sh --target=build
